### ISSUE TITLE
横屏状态下  预览框变形

### ISSUE THREAD

**Issue by 1525685999** [xiaoyaoyou1212/ViseFace#2]

**Comment by 1525685999** [comment]
调用时将activty设置为横屏 ，幕布显示的图像是拉大了的

**Comment by 1525685999** [comment]
大神 ,我是要在安卓电视机上使用，等于是在强制为横屏的activty上使用，请问一下我该怎么做呢?

**Comment by 1525685999** [comment]
/*    if (cameraPreview != null) {
            if (tempW >= width) {
                cameraPreview.setLayoutParams(new FrameLayout.LayoutParams(tempW, height));
                scale = tempW / h;
            } else if (tempH >= height) {
                cameraPreview.setLayoutParams(new FrameLayout.LayoutParams(width, tempH));
                scale = tempH / w;
            } else {
                cameraPreview.setLayoutParams(new FrameLayout.LayoutParams(width, height));
            }
        }*/

我将这一部分代码注释掉后，横向的activty 的预览显示是正常了，但是却检测不到人脸

**Comment by 1525685999** [comment]
大神 您能稍微指点一下吗

**Comment by 1525685999** [comment]
![_15236252515613](https://user-images.githubusercontent.com/17916476/38736806-cfe38c1e-3f5f-11e8-9b21-5cc5230ca4a4.png)

设置Activty横屏状态下  会进入第二个else if中去 ，这时候，展示的效果被拉伸的很模糊，如果直接使用最后一个else里面的判断 则显示正常，但是 却不能检测到人脸了 @xiaoyaoyou1212   能麻烦您给我这个新手稍微解惑一下吗？万分感谢~

**Comment by 1525685999** [comment]
关于上面几个问题 我有了新的进展 ，初始化相机时判断anctivty的方向 为横屏时camera.setDisplayOrientation(result);  参数给90，然后用楼上那张图最后的结果选中  cameraPreview.setLayoutParams(new FrameLayout.LayoutParams(width, height));
接线来在SystemFaceDetector 这个类中
![image](https://user-images.githubusercontent.com/17916476/38766034-98035bea-3ffe-11e8-8a4e-01f7ea02ca8f.png)
把这个条件degrees改为90，之前是0，我试了，必须为90才能够监测到人脸，改了上述的那些条件后，现在还有一个问题 就是绘制人脸框时 没有绘制出来，您有空能稍微指点一两下吗？万分感谢您的这个库，还有代码的封装，受益良多

**Comment by xiaoyaoyou1212** [comment]
@1525685999 不好意思哈，最近一直没有看GitHub，横屏的话相机的方向改变了，所以需要旋转90度，绘制的人脸框其实就是把识别到的坐标展示出来，你可以将坐标点打印出来仔细观察一下看看，应该就能找到问题原因了。

**Comment by 1525685999** [comment]
项目难点终于搞定了，谢谢您提供的代码，给了我很大的参考与帮助，帮助非常之大，谢谢~
